### ISSUE TITLE
dev_appserver.py: command not found

### ISSUE THREAD

**Issue by pauldraper** [trotto/go-links#10]
When running locally

```
./run_local.sh: line 5: dev_appserver.py: command not found
```

**Comment by itsojon** [comment]
Hey @pauldraper! Sorry you hit an issue. If you already installed the `gcloud` [SDK](https://cloud.google.com/sdk/docs), you may also need to run:

```
gcloud components install app-engine-python
```

Let me know if you still get an error. If needed, I can walk through the setup from a fresh environment and debug more deeply.

**Comment by pauldraper** [comment]
Thanks I got that working.

**Comment by itsojon** [comment]
Great, glad to hear it! What was the resolution? I can update the README if needed.

**Comment by pauldraper** [comment]
I didn't realize gcloud was required for both local running and deploying.

(I'm not a GCP guy.)

**Comment by itsojon** [comment]
@pauldraper thank you for explaining what happened.
