### ISSUE TITLE
go-links can no longer deploy to Heroku due to sqlalchemy dropping support to postgres:// URI

### ISSUE THREAD

**Issue by isviridov** [trotto/go-links#100]
Deploying to Heroku today produces:

> 2021-03-28T10:39:46.332245+00:00 app[web.1]:     "Can't load plugin: %s:%s" % (self.group, name)
> 2021-03-28T10:39:46.332354+00:00 app[web.1]: sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres

This is apparently caused by sqlalchemy 1.4.x dropping support for postgres:// URI (keeping only postgresql://):
https://github.com/sqlalchemy/sqlalchemy/issues/6083
https://help.heroku.com/ZKNTJQSK/why-is-sqlalchemy-1-4-x-not-connecting-to-heroku-postgres

Options to fix include:
- pinning SQLAlchemy at 1.3.x (1.3.23)
- implementing URI substitution from postgres:// to postgresql://

**Comment by itsojon** [comment]
@isviridov thank you for flagging this and diagnosing! I'll implement URI substitution now.

**Comment by itsojon** [comment]
@isviridov this is fixed with #101. I just verified deployment of a new app to Heroku works. Thanks again!

**Comment by isviridov** [comment]
Thank you, i confirm it now works well w/Heroku!

**Comment by itsojon** [comment]
Awesome, thank you for confirming, @isviridov!
