### ISSUE TITLE
Delete links

### ISSUE THREAD

**Issue by pauldraper** [trotto/go-links#12]
I don't see a way to delete links.

I mispelled the go link and would like to declutter the list.

**Comment by itsojon** [comment]
Hey @pauldraper! Thank you for bringing this up. Link deletion is actively in the works, and I expect it will be merged into master in 1-2 weeks. Adding it to a self-hosted instance will just require redeploying with the latest version. In the meantime, you can delete a `ShortLink` entity via App Engine's Datastore admin interface if needed.

**Comment by itsojon** [comment]
@pauldraper link deletion has now been merged in. You can check it out at https://latest-master.trotto.dev. If you already have your own instance of Trotto, you'll just need to pull and deploy the latest master.
