### ISSUE TITLE
Search Feature

### ISSUE THREAD

**Issue by ct3685** [trotto/go-links#13]
Would like to see a search functionality so that when I type in go/ that i can just search the list to try to find a specific go link

**Comment by ct3685** [comment]
Also on the directory page but would be super helpful on the initial go/ page

**Comment by itsojon** [comment]
Hey @ct3685! Thank you for submitting this request! To be sure, you'd ideally like to be able to perform this search through the browser extension, in the Chrome omnibar itself, correct?

**Comment by ct3685** [comment]
Sorry, I meant just on this page so that when I type 'go/' it will appear as another option to be able to search instead of creating a new one. This would ideally as I type shorten the list down to available options and not be case-sensitive or if I only typed in 'ca' it would show everything with 'ca' in it and as I type more show less. This would be useful on the directory page as well.

<img width="1019" alt="screenshot" src="https://user-images.githubusercontent.com/50385537/81563991-0ef2e200-9365-11ea-9abc-f6e48d846d0a.png">

**Comment by itsojon** [comment]
Got it, thank you for clarifying! That would definitely help reduce the number of redundant links.

**Comment by ct3685** [comment]
Pretty sure you implemented this and we can close it out. 😎
