### ISSUE TITLE
Allow double hyphens in destination urls

### ISSUE THREAD

**Issue by pompon0** [trotto/go-links#137]
I'm trying to add a go-link in trot.to, of the form "https://double--hyphen.example.com/some/path",
however I get "You must provide a valid destination URL" message. The problem apparently is the "--" infix.

According to RFC1035 a valid domain can have "--" infix (unless RFC 5891 4.2.3.1 applies, which is not the case for my example).
Please fix.

**Comment by coreyward** [comment]
+1 this is preventing us from using Trot.to for some links. Having to work around it by using a link shortener instead. 😞

**Comment by maxtechera** [comment]
@pompon0 - We're working on a new release that will allow these URLs to be valid and will be releasing an update by EOW.

**Comment by maxtechera** [comment]
@pompon0 - This was fixed in #158 and I verified it's now working as expected in production!
