### ISSUE TITLE
Bad 'A conflicting go link already exists' Message

### ISSUE THREAD

**Issue by KyleJamesWalker** [trotto/go-links#164]
When trying to add a few search links to the same domain is says they're conflicting.

Examples that say they conflict:

| go link | full link |
|------|--------|
| https://go/dd/apm/%s | https://app.datadoghq.com/apm/home?search=%s |
| https://go/dd/dash/%s | https://app.datadoghq.com/dashboard/lists?q=%s |
| https://go/dd/logs/%s | https://app.datadoghq.com/logs?query=service%3A%2A%s%2A |

Example Screenshot:
![image](https://user-images.githubusercontent.com/3707079/189216961-5f23997f-03a2-412f-b06a-01a9c28dd918.png)

**Comment by itsojon** [comment]
thank you for reporting this issue, @KyleJamesWalker! we'll ship a fix for this next week.

**Comment by itsojon** [comment]
@KyleJamesWalker give it another try and confirm the fix when you have a chance!

**Comment by KyleJamesWalker** [comment]
Perfection! Thank you so much!

![image](https://user-images.githubusercontent.com/3707079/190727332-e588a805-171e-4eff-bfe0-f5080755f420.png)

**Comment by itsojon** [comment]
awesome, thank you again for creating the issue @KyleJamesWalker!
