### ISSUE TITLE
Issue with python3.7

### ISSUE THREAD

**Issue by carlozt03** [trotto/go-links#191]
Was getting this error running the Docker container: 

```
File "/usr/src/app/server/src/modules/links/handlers.py", line 98, in <module>
links: list[dict[str, Any]],
TypeError: 'type' object is not subscriptable
```

Updated the Dockerfile from `FROM python:3.7-buster` to `FROM python:3.9-buster` helped resolve this issue. Not sure what this will impact, however.

**Comment by itsojon** [comment]
thank you @carlozt03!
