### ISSUE TITLE
Docker file does not compile

### ISSUE THREAD

**Issue by comp615** [trotto/go-links#228]
The dockerfile will not compile for me, it seems related to a version conflict introduced maybe as recent as yesterday between Cython and PYYaml:
https://stackoverflow.com/questions/76708329/docker-compose-no-longer-building-image-attributeerror-cython-sources

The fix is to simply update PyYAML to 6.0.1 in both places (I'm assuming this does not cause breaking changes with the way it's used), which fixed the build and allowed me to progress with setup.

**Comment by itsojon** [comment]
thank you so much, @comp615! we've merged the PyYAML upgrade.
