### ISSUE TITLE
Slashes for Hierarchy Style Links

### ISSUE THREAD

**Issue by ct3685** [trotto/go-links#23]
How hard would it be to add in the functionality of allowing / ? The reason I’m asking is that it would be cool to be able to create our own little structures like go/kb/zoom  would go to the zoom documentation in notion etc

![screenshot](https://user-images.githubusercontent.com/50385537/85792020-c9198f80-b700-11ea-906d-68bda678edfd.png)

Same with the ability for all of Client X’s stuff or any client in general. I feel like if we could somehow map out a hierarchy structure using slashes I could see a lot of potentials there maybe.

Like Client X’s weekly meeting would be go/clientx/weekly or something and the daily standups would be go/clientx/daily and go/clientx/notion or go/clientx/kb or something idk just a thought

**Comment by itsojon** [comment]
@ct3685 thank you for suggesting this! It makes a lot of sense. This type of hierarchical go link would conflict with programmatic go links (that is, there could only be either `go/kb/%s` or `go/kb/zoom` and not both). But I think that's fine with clear error messaging. You could always delete/rename the one if you decide you'd rather have the other.

I'd need to do some design work before estimating the size of this, but I'm guessing it's days at most.

**Comment by itsojon** [comment]
@ct3685 you can now use slashes in your go links! Check it out at https://trot.to, and let me know if you have any questions!
