### ISSUE TITLE
The "go link already exists" message should add a link to the target

### ISSUE THREAD

**Issue by efroese-figma** [trotto/go-links#232]
Sometimes I mistype a go/ link and land on the page to create one.
But then I correct the link in the go/[ text form ].
And I get a message like: 

That go link already exists. go/foo points to https://foo.bar/baz

I would love it if https://foo.bar/baz was an actual link!

**Comment by andykimmay** [comment]
The browser extension has been updated to show that any duplicative go links already exist and it is clickable/an actual link. Users can still create the duplicative go link if desired
