### ISSUE TITLE
Any plan to allow self-hosted domains in Chrome extension? 

### ISSUE THREAD

**Issue by cawarren** [trotto/go-links#3]
I love that this is now open source, it's really helpful for projects that have compliance constraints (e.g., an org I work with has to stay CJIS-compliant, so would prefer to self-host).

That said, the magic really comes from the go/linkness of it. The Chrome extension currently only handles go/ and trot.to, which means it wouldn't work with the self-hosted option today (if I'm understanding correctly). Do you have any plans to enable it to take other domains? Maybe using optional permissions (https://developer.chrome.com/extensions/permission_warnings#optional_events)?

I'm sure it's not on your critical path as a company, so understood if this is not planned.

**Comment by itsojon** [comment]
Hi @cawarren! Thank you for your interest and a great question!

Agreed that the go/linkness is where the magic happens, so making it simple to set that up for any Trotto instance is in fact a priority for us! While we haven't yet publicized/documented this, we did in the past few weeks implement support for overriding the Trotto instance URL via [managed storage](https://developer.chrome.com/apps/storage#property-managed). One of our self-hosting early adopters has been using that option for a few weeks. If your organization is using G Suite, and your users have signed into Chrome with their G Suite accounts, a G Suite admin can configure the Trotto extension through https://admin.google.com/AdminHome?hl=en#ChromeAppList:. Here's an example configuration:

```
{
  "TrottoInstanceUrl": {
    "Value": "https://trotto-test-123.appspot.com"
  }
}
```

We're considering other ways to support overriding the Trotto instance URL, balancing ease of use and security. Likely something along the lines of presenting visitors to any self-hosted instance with the option to explicitly consent to switching their Trotto instance to that particular instance.

**Comment by itsojon** [comment]
@cawarren the Chrome extension (as well as the newer Firefox extension) has been open-sourced at https://github.com/trotto/browser-extension. That repo has a comprehensive README for how to build and test the extension for different browsers and a specific Trotto instance. Let me know if you have any questions or suggestions!
