### ISSUE TITLE
Top nav links in Trot.to/#/ are unresponsive in Chrome / ChromeOS  84.0.4147.110

### ISSUE THREAD

**Issue by jaredzimmerman** [trotto/go-links#36]
The Directory How it Works and Sign out links are unclickable in ChromeOS Chrome browser, you can navigate to them with tab button and they are functional, but you can't click on them with the cursor. The same issue happens with the keyword and link fields below, but inconsistently reproducible, whereas the top nave fails 100% of the time.

**Comment by itsojon** [comment]
@jaredzimmerman thank you for flagging! I can't repro so maybe it's specific to Chrome OS. Are you just looking at the managed instance at trot.to, or another instance? Also, is there anything in the DevTools JS console?

**Comment by jaredzimmerman** [comment]
I just installed the chrome extension...so, yes?

Only think I see in the console is a GA and a Hellobar error

**Comment by jaredzimmerman** [comment]
Ah! figured it out. Adblock was hiding the ProductHunt banner (visually) but the div was still intercepting the clicks for the top nav

![image](https://user-images.githubusercontent.com/430427/89684742-e8830b00-d8af-11ea-97cb-c46ddc220683.png)

**Comment by itsojon** [comment]
@jaredzimmerman I was just starting to suspect that! Sorry for the trouble. I'm about to remove Hello Bar from the app since it was just for the HN launch.
