### ISSUE TITLE
Deploy to DPLYR Docs

### ISSUE THREAD

**Issue by ahmedmgh67** [trotto/go-links#38]
This project can be deployed to [DPLYR](https://www.dplyr.dev) easily, why not add docs for this. I can help you with that

**Comment by itsojon** [comment]
Hey @ahmedmgh67! We won't do this in the immediate term, but let me know if you'd like to document how to deploy Trotto in DPLYR's docs and could use our help. I expect that in time we'll also have a section in our docs linking to resources from the community, which could include a link to any guide you create.
