### ISSUE TITLE
Open-source the Chrome extension

### ISSUE THREAD

**Issue by itsojon** [trotto/go-links#4]
We're in the process of open-sourcing the [Trotto Chrome extension](https://chrome.google.com/webstore/detail/trotto-go-links/nkeoojidblilnkcbbmfhaeebndapehjk) as well. If you're interested in contributing to that project, or if you'd just like to be notified when it's open-sourced, comment on or subscribe to this issue.

**Comment by peterfisher** [comment]
any updates on when this is going to be open sourced? =)

**Comment by itsojon** [comment]
Hey @peterfisher, thank you for reaching out! We did a rough initial release of the open-source extension a little while back, and I just updated the README so that it's considerably more usable: https://github.com/trotto/browser-extension

Let me know if you have any questions! We'll be updating it substantially in the near future as we add Firefox support, and then I think we can call this issue properly complete. Deploying updates to the extension is just a matter of uploading a new zip to the Chrome Web Store and submitting.

**Comment by itsojon** [comment]
Alright, I've updated https://github.com/trotto/browser-extension to:

1. Simplify multi-browser support
2. Make it dead simple to build a version of the extension pointing to another go links instance (whether self-hosted Trotto or another implementation)
3. Add deeper documentation
4. Add Firefox support (see the FF extension we manage at https://addons.mozilla.org/en-US/firefox/addon/trotto-go-links)

I think we can officially call this done!
