### ISSUE TITLE
Infinite Google Auth Redirect

### ISSUE THREAD

**Issue by scottso87** [trotto/go-links#56]
When running the local dev server, the Google OAuth flow is stuck in an infinite loop, never logging in but redirecting back to the auth screen.

**Comment by itsojon** [comment]
@scottso87 sorry to hear you ran into this issue! I'll take a look and try to reproduce the issue shortly. We'll get to the bottom of it.

**Comment by itsojon** [comment]
@scottso87 I think I found the issue. Fix incoming.

**Comment by itsojon** [comment]
Alright, this should be fixed. @scottso87 can you pull the latest version and confirm you can now log into the local dev server?

**Comment by scottso87** [comment]
That worked! Much appreciated, @itsojon

**Comment by itsojon** [comment]
@scottso87 awesome! Thank you for reporting this!
