### ISSUE TITLE
Replica support - multiple k8s pods

### ISSUE THREAD

**Issue by jmcfallargo** [trotto/go-links#82]
I haven't tested this, but I am not sure if the app is known to work with multiple instances, in say a k8s load balanced scenario using PG for the DB.
If not, what do you think some of the areas of code would prevent this.
I am looking to balance the load along with handling cases with a node is drained

Thanks!

**Comment by itsojon** [comment]
Hey @jmcfallargo! Yes, I expect that will work fine--we scale the managed service (https://trot.to) up to multiple instances with Postgres.

If you end up setting up Trotto with k8s, I'd welcome any code/config you'd be willing to contribute back to the project. Let me know if you have any other questions along the way.

**Comment by jmcfallargo** [comment]
Thanks for the info @itsojon and thanks for the work on the project.  I will try to submit my changes for sure.

**Comment by itsojon** [comment]
@jmcfallargo you're very welcome! Sounds good; here to help.
